--- # Model hyper-parameters.
loss: sparse_categorical_crossentropy
optimizer:
  name: Adam
  learning_rate: 0.0001
  beta_1: 0.9
  beta_2: 0.95
  amsgrad: No
metrics: [SPARSE_CAT_ACCURACY]
batch_size: 2
epochs: 10
shape_format: channels_last
input_shape: [112, 112, 3]
weights: